name: HetimaPortMap
version: 0.0.031
author: kyorohiro
description: port map chrome app
dependencies:
  chrome: any
  dart_web_toolkit: any
  hetima:
    git: https://github.com/kyorohiro/dart_hetimalib.git
transformers:
- chrome
csp: false;