name: HetimaPortMap
version: 0.0.031
author: kyorohiro
description: port map chrome app
dependencies:
  chrome: any
  dart_web_toolkit: any
  hetima:
    path: /Users/kiyohiro/dart/git/dart_hetimalib
transformers:
- chrome
