name: HetimaPortMap
version: 0.0.033
author: kyorohiro
description: port map chrome app
dependencies:
  chrome: any
  dart_web_toolkit: any
  hetima:
    git: https://github.com/kyorohiro/dart_hetimalib.git
transformers:
- chrome
- $dart2js:
    csp: true