name: HetimaPortMap
version: 0.0.033
author: kyorohiro
description: port map chrome app
dependencies:
  chrome: any
  dart_web_toolkit: any
  hetimacore:
    git: https://github.com/kyorohiro/dart_hetimacore
  hetimanet:
    path: /Users/kiyohiro/dart/git/dart_hetimanet
transformers:
- chrome
- $dart2js:
    csp: true
